import os
import sys
from youtube_upload import YouTubeUploader

def upload_video_now(gcs_uri, title=None, description=None, tags=None):
    print("Commencing GCS upload...")
    # Get the project root directory (one level up from the current file's directory)
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    credentials_path = os.path.join(project_root, 'hosts', 'cli', 'credentials.json')
    uploader = YouTubeUploader(credentials_path=credentials_path)
    
    try:
        response = uploader.upload_from_gcs(
            gcs_uri=gcs_uri,
            title=title or "Video generated by Veo3",
            description=description or "This is an upload from Google Cloud Storage",
            tags=tags or ["test", "gcs", "upload"],
            privacy_status="public"  # Changed from "private" to "public"
        )
        print(f"Success! Video uploaded with ID: {response['id']}")
        print(f"Video URL: https://youtu.be/{response['id']}")
        return True
    except Exception as e:
        print(f"Error during GCS upload: {str(e)}")
        return False

if __name__ == "__main__":
    # Require GCS URI as command line argument
    # Example usage: python test_upload.py gs://your-bucket/your-video.mp4
    if len(sys.argv) > 1:
        gcs_uri = sys.argv[1]
        if gcs_uri.startswith('gs://'):
            upload_video_now(gcs_uri)
        else:
            print("\nError: Invalid GCS URI. It should start with 'gs://'")
            print("Example: python test_upload.py gs://your-bucket/path/to/video.mp4")
            sys.exit(1)
    else:
        print("\nError: GCS URI is required")
        print("Usage: python test_upload.py gs://your-bucket/path/to/video.mp4")
        sys.exit(1)
